#!/usr/bin/perl
#
# Copyright (C) 2020 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use esmith::Build::CreateLinks  qw(:all);

my $event;

# mssql update event

$event = "nethserver-mssql-update";

event_actions($event, qw(
  initialize-default-databases 00
));

# mssql save event

$event = "nethserver-mssql-save";

event_actions($event, qw(
  nethserver-mssql-install 10
  nethserver-mssql-setup 20
  nethserver-mssql-tools 30
));

event_services($event, qw(
  mssql-server restart
  shorewall reload
));

# pre-backup-data

$event = "pre-backup-data";

event_actions($event, qw(
  mssql-dump-tables 50
));

# post-backup-data

$event = "post-backup-data";

event_actions($event, qw(
  mssql-delete-dumped-tables 50
));

# post-restore-config

$event = "post-restore-config";

event_actions($event, qw(
  nethserver-mssql-restore-config 50
));

# post-restore-data

$event = "post-restore-data";

event_actions($event, qw(
  mssql-restore-tables 10
  mssql-delete-dumped-tables 60
));

event_services($event, qw(
  mssql-server restart
));
