#!/usr/bin/perl

#
# Copyright (C) 2020 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use warnings;
use esmith::ConfigDB;
use NethServer::Password;

require '/usr/libexec/nethserver/api/lib/helper_functions.pl';

my $input = readInput();
my $cmd = $input->{'action'};

my $ret = {};

if ($cmd eq 'configuration') {
  
  my $out = `rpm -q --quiet mssql-server`;
  
  if ($? == 0) {
    
    $ret->{'configuration'}{'installed'} = 1;
        
    $out = `systemctl is-active mssql-server`;
    $ret->{'configuration'}{'isrunning'} = ($? == 0)? 1 : 0;
    
  } else {
    $ret->{'configuration'}{'installed'} = 0;
  }
  
  my $db = esmith::ConfigDB->open_ro();
  $ret->{'configuration'}{'ProductId'} = $db->get_prop('mssql-server', 'ProductId') || 'Express';
  $ret->{'configuration'}{'ProductKey'} = $db->get_prop('mssql-server', 'ProductKey') || '';
  
  my $password = NethServer::Password::store("mssql");
  $ret->{'configuration'}{'sapassword'} = $password;
  
} else {
    error();
}

print encode_json($ret);