#!/usr/bin/perl

#
# Copyright (C) 2020 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use esmith::ConfigDB;
use esmith::event;
use JSON;

require '/usr/libexec/nethserver/api/lib/helper_functions.pl';

my $eventName = undef;
my $ret;
my $exitCode = 0;

my $db = esmith::ConfigDB->open();

my $input = readInput();
my %props = ();

   %props = (
      'ProductId' => $input->{'configuration'}->{'ProductId'},
      'ProductKey' => $input->{'configuration'}->{'ProductKey'}
    );
    
if($input->{'action'} eq 'edit') {
    $db->get('mssql-server')->merge_props(%props);
} elsif ($input->{'action'} ne 'change-password') {
    error();
}

esmith::event::set_json_log(1);

if($input->{'action'} eq 'edit') {

  if (esmith::event::event_signal('nethserver-mssql-save')) {
      $ret = {'state' => 'success'};
  } else {
      $ret = {
          'type' => 'Error',
          'message' => 'mssql.api_update_failed',
          'attributes' => {
              'event_name' => 'nethserver-mssql-save'
          }
      };
      $exitCode = 1;
  }
  
} elsif ($input->{'action'} eq 'change-password') {
  
  my $newpassword = $input->{'password'}->{'newPassword'};
  print $newpassword;
  
  if (esmith::event::event_signal('nethserver-mssql-change-password',$newpassword)) {
      $ret = {'state' => 'success'};
  } else {
      $ret = {
          'type' => 'Error',
          'message' => 'mssql.api_update_failed',
          'attributes' => {
              'event_name' => 'nethserver-mssql-change-password'
          }
      };
      $exitCode = 1;
  }
  
}

print encode_json($ret);
exit($exitCode);