#!/usr/bin/php
<?php
  
/*
 * Copyright (C) 2020 Nethesis S.r.l.
 * http://www.nethesis.it - nethserver@nethesis.it
 *
 * This script is part of NethServer.
 *
 * NethServer is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License,
 * or any later version.
 *
 * NethServer is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with NethServer.  If not, see COPYING.
*/

require_once("/usr/libexec/nethserver/api/lib/users_functions.php");


function validateEdition($data) {
  $v = new LegacyValidator($data['configuration']);
  if ($data['configuration']['ProductId'] == 'key') {
    $key = $data['configuration']['ProductKey'];
    $arr = explode("-",$key);
    if (count($arr) != 5 || strlen($arr[0]) != 5 || strlen($arr[1]) != 5 || strlen($arr[2]) != 5 || strlen($arr[3]) != 5 || strlen($arr[4]) != 5) {
      $v->addValidationError('ProductKey', 'NotValidProductKey', $v->parameters['ProductKey']);
    }
  }

  if ($v->validate()) {
    success();
  } else {
    error($v);
  }
}

function validatePassword($data) {
  $v = new LegacyValidator($data['password']);
  
  check_password($data, $v);

  if ($v->validate()) {
    success();
  } else {
    error($v);
  }
}

$data = readInput();

if($data['action'] == 'edit') {
    validateEdition($data);
} else if($data['action'] == 'change-password') {
    validatePassword($data);
} else {
    error();
}