#!/bin/bash

#
# Copyright (C) 2020 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

# check if mssql is configured
if [[ ! -f /var/opt/mssql/data/master.mdf ]]; then
  exit 0
fi

# get new user password
NEWPASSWORD=$1

# get current password
CURPASSWORD=$(cat /var/lib/nethserver/secrets/mssql)

if [[ ! ${NEWPASSWORD} ]]; then
  echo "No password specified"
  exit 0
fi

# change password into master db
RESULT=$(/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P ${CURPASSWORD} -Q "
ALTER LOGIN [SA] WITH PASSWORD = N'${NEWPASSWORD}';" 2>&1)

if [ -z "${RESULT}" ]; then
  # change password into nethserver secrets/mssql
  echo ${NEWPASSWORD} > /var/lib/nethserver/secrets/mssql

  # show message to user
  echo "Password changed"
else
  # show result
  echo "ERROR: ${RESULT}"
fi