#!/bin/bash

#
# Copyright (C) 2020 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

# check if mssql is configured
if [[ ! -f /var/opt/mssql/data/master.mdf ]]; then
  exit 0
fi

if systemctl is-active --quiet mssql-server.service; then
  # stop mssql-server if is active
  systemctl stop mssql-server.service
  
  # wait mssql stop
  sleep 5
fi

# get new user password
NEWPASSWORD=$1

if [[ ! ${NEWPASSWORD} ]]; then
  echo "No password specified"
  exit 0
fi

# change password into master db
RESULT=$(MSSQL_SA_PASSWORD=${NEWPASSWORD} /opt/mssql/bin/mssql-conf set-sa-password 2>&1)

if [ $? -eq 0 ]; then
  # change password into nethserver secrets/mssql
  echo ${NEWPASSWORD} > /var/lib/nethserver/secrets/mssql

  # show message to user
  echo "Password changed"
else
  # show result
  echo "ERROR: ${RESULT}"
fi

# starting mssql-server
systemctl start mssql-server.service