#!/bin/bash

#
# Copyright (C) 2020 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

PRODUCT=$(/sbin/e-smith/config getprop mssql-server ProductId)
KEY=$(/sbin/e-smith/config getprop mssql-server ProductKey)

if [ ${PRODUCT} = "key" ]; then
  PID=${KEY}
else
  PID=${PRODUCT}
fi

# create a new password for mssql
perl -e "use esmith::util; 
         use NethServer::Password; 
         NethServer::Password::store('mssql');"

PASSWORD=$(cat /var/lib/nethserver/secrets/mssql)

# setup mssql-server
MSSQL_SA_PASSWORD=${PASSWORD} MSSQL_PID=${PID} SQL_ENABLE_AGENT='y' /opt/mssql/bin/mssql-conf -n setup accept-eula

# enable mssql-server on boot
/sbin/e-smith/config setprop mssql-server status enabled

# enable sqlagent
/opt/mssql/bin/mssql-conf set sqlagent.enabled true