#!/usr/bin/perl

#
# Copyright (C) 2020 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use esmith::event;
use JSON;
use NethServer::Password;

require '/usr/libexec/nethserver/api/lib/helper_functions.pl';

my $ret;
my $exitCode = 0;
my $password = NethServer::Password::store("mssql");

my $input = readInput();

if ($input->{'action'} eq 'create-database') {
    my $dbname = $input->{'newDatabase'}->{'name'};
    my $out = `/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P $password -h -1 -Q "CREATE DATABASE $dbname"`;
    
    if ($? == 0) {
      $ret = {'state' => 'success'};
    } else {
      $ret = {
          'type' => 'Error',
          'message' => 'mssql.api_update_failed',
          'attributes' => {
              'event_name' => 'create-database'
          }
      };
      $exitCode = 1;
    }
} else {
    error();
}

print encode_json($ret);
exit($exitCode);