#!/usr/bin/php
<?php
  
/*
 * Copyright (C) 2020 Nethesis S.r.l.
 * http://www.nethesis.it - nethserver@nethesis.it
 *
 * This script is part of NethServer.
 *
 * NethServer is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License,
 * or any later version.
 *
 * NethServer is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with NethServer.  If not, see COPYING.
*/

require_once("/usr/libexec/nethserver/api/lib/Helpers.php");

function validateDatabase($data) {
  $v = new LegacyValidator($data['newDatabase']);
  
  $password = trim(shell_exec("cat /var/lib/nethserver/secrets/mssql"));
  $out = trim(shell_exec("/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P \"".$password."\" -h -1 -Q 'SET NOCOUNT ON; SELECT COUNT(*) FROM sys.databases WHERE name = \"".$data['newDatabase']['name']."\"'"));

  if ($out > 0) {
    $v->addValidationError('newDatabase', 'DbAlreadyExists', $v->parameters['name']);
  }

  if ($v->validate()) {
    success();
  } else {
    error($v);
  }
}

$data = readInput();

if($data['action'] == 'create-database') {
    validateDatabase($data);
} else {
    error();
}